name: Deploy RepoA to Server

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the RepoA code
      - name: Checkout RepoA
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Build RepoA as a dist package
      - name: Build RepoA
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python setup.py sdist
          ls ./dist  # Debug to ensure the dist package is created

      # Step 4: Add SSH Key for Deployment
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 5: Prepare the EC2 Server for Deployment
      - name: Prepare Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            set -e
            # Ensure RepoA dist directory exists and is clean
            mkdir -p /home/ubuntu/RepoA/dist
            rm -rf /home/ubuntu/RepoA/dist/*
          EOF

      # Step 6: Copy the Dist Package to the EC2 Server
      - name: Copy Dist Package to Server
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./dist/*.tar.gz ubuntu@${{ secrets.AWS_EC2_IP }}:/home/ubuntu/RepoA/dist/

      # Step 7: Install the Dist Package on the Server
      - name: Install RepoA on Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            set -e
            # Navigate to the MainRepo directory
            cd /home/ubuntu/MainRepo
      
            # Pull the latest changes for MainRepo
            git reset --hard
            git pull origin main
      
            # Activate the virtual environment
            source /home/ubuntu/MainRepo/venv/bin/activate
      
            # Install the updated RepoA package
            pip install /home/ubuntu/RepoA/dist/*.tar.gz
      
            # Restart the MainRepo-related services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
      # Step 8: Trigger the Main Repo Pipeline
      - name: Trigger Main Repo Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/aabouzaid96/MainRepo/actions/workflows/deploy.yaml/dispatches \
            -d '{"ref":"main"}'