name: Deploy RepoA to Server

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # Run your build or tests (Optional)
      - name: Run Tests (Optional)
        run: |
          pytest  # Replace with your test framework

      # SSH into the server and deploy
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            set -e

            # Navigate to RepoA directory on the server
            cd /home/ubuntu/RepoA

            # Pull the latest changes
            git reset --hard
            git pull origin main

            # Activate the virtual environment
            source /path/to/venv/bin/activate

            # Install RepoA
            python setup.py install

            # Restart any services or apply changes
            sudo systemctl restart some-service  # Replace with the actual service
          EOF

      # Debugging step to verify SSH connection and actions
      - name: Debug SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} echo "SSH successful"
